# Setup
title:               Chris Rockwell
tagline:             ''
description:         'Software architecture, engineering, and development.'
url:                 https://chrisrockwell.com
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Chris Rockwell
  url:               https://chrisrockwell.com
  email:             chris@chrisrockwell.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
